import { useState } from 'react'
import { getPromptPackFields } from '../data/promptPacks'

// Renders a saved prompt pack (provider-specific prompts generated by
// PromptPackComposer) with a field switcher + copy — shared by the drafts
// list (imageless concepts) and ConceptViewer's info panel.
export default function SavedPromptPack({ promptPack }) {
  const [activeField, setActiveField] = useState('')
  const [copied, setCopied] = useState('')
  const fields = getPromptPackFields(promptPack)
  if (!fields.length) return null

  const active = fields.find((field) => field.field === activeField) || fields[0]

  async function copySavedPrompt() {
    try {
      await navigator.clipboard.writeText(active.value)
      setCopied(active.field)
      setTimeout(() => setCopied(''), 1600)
    } catch {
      // clipboard unavailable — the textarea below still lets the user select + copy manually
    }
  }

  return (
    <div className="mb-6 pb-6 border-b border-v2-hairline">
      <p className="font-v2-ui text-xs tracking-widest uppercase text-v2-accent mb-2">Saved prompt pack</p>
      <div className="flex flex-wrap gap-1.5 mb-2">
        {fields.map((field) => (
          <button
            key={field.id}
            onClick={() => setActiveField(field.field)}
            className={`font-v2-ui text-[0.625rem] tracking-widest uppercase rounded-sm border px-2 py-1 transition-colors ${
              active.field === field.field ? 'border-v2-accent text-v2-cream' : 'border-v2-hairline text-v2-muted hover:text-v2-cream'
            }`}
          >
            {field.label}
          </button>
        ))}
      </div>
      <textarea
        readOnly
        rows={5}
        value={active.value}
        className="w-full bg-v2-ink border border-v2-hairline rounded-sm px-3 py-2 font-v2-ui text-xs text-v2-muted resize-none"
      />
      <button
        onClick={copySavedPrompt}
        className="mt-2 font-v2-ui text-[0.625rem] tracking-widest uppercase text-v2-accent hover:text-v2-cream"
      >
        {copied === active.field ? 'Copied' : `Copy ${active.label}`}
      </button>
    </div>
  )
}
